### PR TITLE
Update plot - Fix

### PR DESCRIPTION
**Pull request by addUsername**
Closed [previous PR](https://github.com/narvikd/sha512sum/pull/6) to fix a bug

## What?
- Changed plot orientation, now y-axis groups bars by files  and colored bars identify the method
- Change to night theme, set transparent background and white color for borders, ticks and font
## Why?
Seems better
## How?

``` python
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import numpy as np

df = pd.DataFrame(dict(graph=['#10000\n0.1 mb', '#1000\n10mb', "#20\n700 mb"],
                           unix = [3.35, 33.35, 41.96],go = [2.51, 25.82, 30.24], routines = [0.96, 19.62, 19.68],workpool = [2.47, 20.60, 27.44])) 

COLOR = 'white'
mpl.rcParams['text.color'] = COLOR
mpl.rcParams['axes.labelcolor'] = COLOR
mpl.rcParams['xtick.color'] = COLOR
mpl.rcParams['ytick.color'] = COLOR

ind = np.arange(len(df))
width = .200
margin = 0.1

fig, ax = plt.subplots()
fig.suptitle('Benchmark results',  fontsize=20)
plt.xlabel('time (s)', fontsize=16)
plt.ylabel('# files & size',  fontsize=16)

ax.barh(ind - width , df.unix, width, color="#ffe74c", label='Unix')
ax.barh(ind , df.go, width, color="#ff5964", label='Single\nthread go')
ax.barh(ind + width , df.routines, width, color="#38618c", label='Go\nroutines')
ax.barh(ind + width*2 , df.workpool, width, color="#8cdba1", label="Workpool")

ax.set(yticks=ind + width, yticklabels=df.graph, ylim=[2*width - 1, len(df)])

legend = plt.legend(edgecolor="white")
legend.get_frame().set_alpha(None)
legend.get_frame().set_facecolor((1, 1, 1, 0.1))

plt.tight_layout()
plt.savefig('fig_2.png', transparent=True)
plt.show()
```

### CODE REVIEW

**Comment by narvikd** [comment]
Hello, I can't see it properly with a black background.
Could you take a look at it?.

Thank you.

image

**Comment by addUsername** [comment]
That's odd, I wasn't able to reproduce the view either in Chrome or Firefox. I will set a black background color instead a transparent one.

**Comment by addUsername** [comment]
Plot code keeps growing, added here as reference for future fixies, like that bar value outside box
``` python
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import numpy as np

# Check MatPlotLib version
values_end_bar = True
int, dec = mpl.__version__.split(".")[:2]

if(float(int+"."+dec) < 3.4):
    print("Please update MatPlotLib version to + 3.4 to see values at the end of each bar\n\t  pip install matplotlib==3.4 -U")
    values_end_bar = False

# Data
df = pd.DataFrame(dict(graph=['#10000\n0.1 mb', '#1000\n10mb', "#20\n700 mb"],
                           unix = [3.35, 33.35, 41.96],
                           go = [2.51, 25.82, 30.24],
                           routines = [0.96, 19.62, 19.68],
                           workpool = [2.47, 20.60, 27.44]))

COLOR_BLACK = "#22272e"

# Data color
COLOR = 'white'
mpl.rcParams['text.color'] = COLOR
mpl.rcParams['axes.labelcolor'] = COLOR
mpl.rcParams['xtick.color'] = COLOR
mpl.rcParams['ytick.color'] = COLOR
plt.rcParams['axes.facecolor'] = COLOR_BLACK

# Figure
fig, ax = plt.subplots()
fig.suptitle('Benchmark results',  fontsize=20)
plt.xlabel('time (s)', fontsize=16)
plt.ylabel('# files & size',  fontsize=16)

# Constants
ind = np.arange(len(df))
width = .200
margin = 0.1

# background color
fig.patch.set_facecolor(COLOR_BLACK)

# axis color
for spine in ax.spines.values():
        spine.set_edgecolor('white')

# Horizontal bars
ax.barh(ind - width , df.unix, width, color="#ffe74c", label='Unix')
ax.barh(ind , df.go, width, color="#ff5964", label='Single\nthread go')
ax.barh(ind + width , df.routines, width, color="#38618c", label='Go\nroutines')
ax.barh(ind + width*2 , df.workpool, width, color="#8cdba1", label="Workpool")

# Left labels
ax.set(yticks=ind + width, yticklabels=df.graph, ylim=[2*width - 1, len(df)])

# add bar value at the end
if(values_end_bar):
    for container in ax.containers:
        plt.bar_label(container, label_type='edge', padding=10)


legend = plt.legend(edgecolor="white")
legend.get_frame().set_alpha(None)
legend.get_frame().set_facecolor((1, 1, 1, 0.1))

plt.tight_layout()
plt.savefig('fig_2.png', transparent=False)
```

**Comment by narvikd** [comment]
Thank you for the code!

**Comment by narvikd** [comment]
It looks amazing, thank you so much yet again. I really appreciate your hard work.

**Comment by addUsername** [comment]
Anytime! Amazing repo, keep up the good work.

**Comment by narvikd** [comment]
Thank you ^^!

**Pull request merged**
